version: '3.8'
services:
  wa-gateway:
    image: gateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"